In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import confusion_matrix

# 1 - Modelo de Classificação Linear

In [90]:
# Inicialização do LDA
lda = LinearDiscriminantAnalysis()

In [94]:
# Carregando conjunto de treino e teste
treino = pd.read_excel('Homework03/hw3-data/cls_trated_train_set.xlsx')
teste = pd.read_excel('Homework03/hw3-data/cls_trated_test_set.xlsx')

In [95]:
# Organizando os conjuntos
treino = treino.drop(columns=['Unnamed: 0'])
teste = teste.drop(columns=['Unnamed: 0'])
x_treino = treino.T.iloc[0:-1]
y_treino = treino['MOS']
x_teste = teste.T.iloc[0:-1]
y_teste = teste['MOS']
x_treino,x_teste,y_treino,y_teste = x_treino.T,x_teste.T,y_treino.T,y_teste.T

In [128]:
lda.fit(x_treino,y_treino) # Treinando o LDA
pred = lda.predict(x_teste) # Testando o LDA
CM = confusion_matrix(y_teste,pred) # Cálculo da confusion matrix
pont = lda.score(x_teste,y_teste) # Cálculo da precisão
print(f'A análise de discriminante linear conseguiu prever {100*pont:.4}% das amostras')
print(f'\nConfusion Matrix: \n {CM}')

A análise de discriminante linear conseguiu prever 57.42% das amostras

 Confusion Matrix: 
 [[1363  659    8    0   15]
 [ 182 1188    1    0    4]
 [ 163   27    8    0   18]
 [  15  104    3    0    1]
 [ 416  300   16    0   46]]


# 2 - Modelo de Classificação não Linear

## 2.1 - Análise de discriminante quadratico